import { WEAPON_ACCESS_CLASSES } from './classes';
import type { CatalogItem, ItemRestrictions } from './types';

const WEAPON_RESTRICTIONS: ItemRestrictions = {
  classes: WEAPON_ACCESS_CLASSES,
};

export const ITEM_CATALOG: CatalogItem[] = [
  {
    id: 'Knife',
    name: 'Knife',
    slot: 'Weapon',
    capacity: 0,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 1, control: -1 } },
    description: 'Rarity: scrap_tech. +1 STR, -1 CTR.',
  },
  {
    id: 'Mace',
    name: 'Mace',
    slot: 'Weapon',
    capacity: 0,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 1, utility: -1 } },
    description: 'Rarity: scrap_tech. +1 STR, -1 UTL.',
  },
  {
    id: 'Taser',
    name: 'Taser',
    slot: 'Weapon',
    capacity: 0,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { technique: 1, control: -1 } },
    description: 'Rarity: market. +1 TEQ, -1 CTR.',
  },
  {
    id: 'Helmet',
    name: 'Helmet',
    slot: 'Costume',
    capacity: 0,
    effects: { set: {}, alter: { vitality: 1, technique: -1 } },
    description: 'Rarity: market. +1 VIT, -1 TEQ.',
  },
  {
    id: 'Lucky Charm',
    name: 'Lucky Charm',
    slot: 'Gadget',
    capacity: 0,
    effects: { set: { utility: 3, control: 1 }, alter: {} },
    description: 'Rarity: market. =3 UTL, =1 CTR.',
  },
  {
    id: 'Sword',
    name: 'Sword',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 1 } },
    description: 'Rarity: market. +1 STR.',
  },
  {
    id: 'Pistol',
    name: 'Pistol',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: { strength: 4 }, alter: { control: 1 } },
    description: 'Rarity: market. =4 STR, +1 CTR.',
  },
  {
    id: 'Spear',
    name: 'Spear',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { control: 1 } },
    description: 'Rarity: market. +1 CTR.',
  },
  {
    id: 'Baseball Bat',
    name: 'Baseball Bat',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { technique: 1 } },
    description: 'Rarity: scrap_tech. +1 TEQ.',
  },
  {
    id: 'Crossbow',
    name: 'Crossbow',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { control: 2, technique: -1 } },
    description: 'Rarity: expensive. +2 CTR, -1 TEQ.',
  },
  {
    id: 'Brass Knuckles',
    name: 'Brass Knuckles',
    slot: 'Weapon',
    capacity: 1,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 1, technique: 1, vitality: -1 } },
    description: 'Rarity: market. +1 STR, +1 TEQ, -1 VIT.',
  },
  {
    id: 'Homemade Costume',
    name: 'Homemade Costume',
    slot: 'Costume',
    capacity: 1,
    effects: { set: {}, alter: { vitality: 1, utility: -1 } },
    description: 'Rarity: scrap_tech. +1 VIT, -1 UTL.',
  },
  {
    id: 'Basic Costume',
    name: 'Basic Costume',
    slot: 'Costume',
    capacity: 1,
    effects: { set: {}, alter: { vitality: 2 } },
    description: 'Rarity: market. +2 VIT.',
  },
  {
    id: 'Heavy Costume',
    name: 'Heavy Costume',
    slot: 'Costume',
    capacity: 1,
    effects: { set: {}, alter: { vitality: 3, technique: -1 } },
    description: 'Rarity: market. +3 VIT, -1 TEQ.',
  },
  {
    id: 'Light Costume',
    name: 'Light Costume',
    slot: 'Costume',
    capacity: 1,
    effects: { set: {}, alter: { vitality: 1, control: 1 } },
    description: 'Rarity: market. +1 VIT, +1 CTR.',
  },
  {
    id: 'Smoke Grenade',
    name: 'Smoke Grenade',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: { control: 3 }, alter: {} },
    description: 'Rarity: market. =3 CTR.',
  },
  {
    id: 'Pipe Bomb',
    name: 'Pipe Bomb',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: {}, alter: { control: 1 } },
    description: 'Rarity: scrap_tech. +1 CTR.',
  },
  {
    id: 'Grappling Hook',
    name: 'Grappling Hook',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: {}, alter: { control: 2, vitality: -1 } },
    description: 'Rarity: expensive. +2 CTR, -1 VIT.',
  },
  {
    id: 'Utility Belt',
    name: 'Utility Belt',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: {}, alter: { utility: 1, strength: -1 } },
    description: 'Rarity: expensive. +1 UTL, -1 STR.',
  },
  {
    id: 'Molotov',
    name: 'Molotov',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: {}, alter: { strength: 2, vitality: -1 } },
    description: 'Rarity: scrap_tech. +2 STR, -1 VIT.',
  },
  {
    id: 'Shield',
    name: 'Shield',
    slot: 'Gadget',
    capacity: 1,
    effects: { set: {}, alter: { vitality: 1 } },
    description: 'Rarity: expensive. +1 VIT.',
  },
  {
    id: 'Laser Gun',
    name: 'Laser Gun',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 1, control: 1 } },
    description: 'Rarity: tinker_tech. +1 STR, +1 CTR.',
  },
  {
    id: 'Grenade Launcher',
    name: 'Grenade Launcher',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: { strength: 6 }, alter: { vitality: -2 } },
    description: 'Rarity: fortune. =6 STR, -2 VIT.',
  },
  {
    id: 'Flamethrower',
    name: 'Flamethrower',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 3, technique: -1 } },
    description: 'Rarity: fortune. +3 STR, -1 TEQ.',
  },
  {
    id: 'Sniper Rifle',
    name: 'Sniper Rifle',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: { strength: 5 }, alter: { control: -2 } },
    description: 'Rarity: expensive. =5 STR, -2 CTR.',
  },
  {
    id: 'Assault Rifle',
    name: 'Assault Rifle',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: { strength: 4 }, alter: { control: 1 } },
    description: 'Rarity: expensive. =4 STR, +1 CTR.',
  },
  {
    id: 'Buster Sword',
    name: 'Buster Sword',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 2 } },
    description: 'Rarity: tinker_tech. +2 STR.',
  },
  {
    id: 'Plasma Blade',
    name: 'Plasma Blade',
    slot: 'Weapon',
    capacity: 2,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: {}, alter: { strength: 3, vitality: -1 } },
    description: 'Rarity: tinker_tech. +3 STR, -1 VIT.',
  },
  {
    id: 'Personalized Costume',
    name: 'Personalized Costume',
    slot: 'Costume',
    capacity: 2,
    effects: { set: {}, alter: { utility: 1, vitality: 1 } },
    description: 'Rarity: premium. +1 UTL, +1 VIT.',
  },
  {
    id: 'Steel Plate',
    name: 'Steel Plate',
    slot: 'Costume',
    capacity: 2,
    effects: { set: {}, alter: { vitality: 4, control: -1 } },
    description: 'Rarity: fortune. +4 VIT, -1 CTR.',
  },
  {
    id: 'Power Armor',
    name: 'Power Armor',
    slot: 'Costume',
    capacity: 2,
    effects: { set: {}, alter: { strength: 2, vitality: 2, control: -1, technique: -1 } },
    description: 'Rarity: tinker_tech. +2 STR, +2 VIT, -1 CTR, -1 TEQ.',
  },
  {
    id: 'Jetpack',
    name: 'Jetpack',
    slot: 'Gadget',
    capacity: 2,
    effects: { set: {}, alter: { control: 2 } },
    description: 'Rarity: tinker_tech. +2 CTR.',
  },
  {
    id: 'Enhancer Drugs',
    name: 'Enhancer Drugs',
    slot: 'Gadget',
    capacity: 2,
    effects: { set: {}, alter: { strength: 1, vitality: 3, control: 2, utility: -2, technique: -1 } },
    description: 'Rarity: fortune. +1 STR, +3 VIT, +2 CTR, -2 UTL, -1 TEQ.',
  },
  {
    id: 'Kevlar Covering',
    name: 'Kevlar Covering',
    slot: 'Gadget',
    capacity: 2,
    effects: { set: {}, alter: { vitality: 2 } },
    description: 'Rarity: expensive. +2 VIT.',
  },
  {
    id: 'Recon Drone',
    name: 'Recon Drone',
    slot: 'Gadget',
    capacity: 2,
    effects: { set: {}, alter: { utility: 2, control: -1 } },
    description: 'Rarity: premium. +2 UTL, -1 CTR.',
  },
  {
    id: 'Nanofilament Blade',
    name: 'Nanofilament Blade',
    slot: 'Weapon',
    capacity: 3,
    restrictions: WEAPON_RESTRICTIONS,
    effects: { set: { control: 4 }, alter: { strength: 4 } },
    description: 'Rarity: tinker_tech. +4 STR, =4 CTR.',
  },
  {
    id: 'Mecha Suit',
    name: 'Mecha Suit',
    slot: 'Costume',
    capacity: 3,
    effects: { set: { strength: 5, vitality: 9 }, alter: { control: 1, technique: -1 } },
    description: 'Rarity: tinker_tech. =5 STR, =9 VIT, +1 CTR, -1 TEQ.',
  },
  {
    id: 'Titan Armor',
    name: 'Titan Armor',
    slot: 'Costume',
    capacity: 3,
    effects: { set: {}, alter: { vitality: 6 } },
    description: 'Rarity: premium. +6 VIT.',
  },
  {
    id: 'Combat Analyzer AI',
    name: 'Combat Analyzer AI',
    slot: 'Gadget',
    capacity: 3,
    effects: { set: { technique: 5 }, alter: { control: -2, utility: 3 } },
    description: 'Rarity: premium. =5 TEQ, -2 CTR, +3 UTL.',
  },
  {
    id: 'Precog Forecast',
    name: 'Precog Forecast',
    slot: 'Gadget',
    capacity: 3,
    effects: { set: {}, alter: { control: 4 } },
    description: 'Rarity: premium. +4 CTR.',
  },
];
